name: Build Flutter APKs & Appbundle
on: push

jobs:
  build_documentation: 
    name: Build Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'     

      - name: Flutter pub get
        run: flutter pub get

      - name: Install dartdoc
        run: flutter pub global activate dartdoc

      - name: Generate documentation
        run: flutter pub global run dartdoc

      - name: Release the documentation
        uses: crazy-max/ghaction-github-pages@v3
        if: success()
        with:
          target_branch: documentation
          build_dir: doc/api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  # Build APKs
  build_apks:
    name: Build APKs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21.x'

      - name: Initialize project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'     

      - name: Building APKs (Split by ABI)
        run: flutter build apk --release --split-per-abi
 
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifacts
          path: build/app/outputs/flutter-apk/*.apk
          overwrite: true
  # Build Appbundle
  build_appbundle:
    name: Build APPBUNDLE
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '21.x'

      - name: Get project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'    

      - name: Building Appbundle
        run: flutter build appbundle

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: publish-artifacts
          path: build/app/outputs/bundle/release/*.aab
          overwrite: true


  publish:
    name: Publish the binaries
    needs: [build_apks, build_appbundle]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 

      - name: Get project version
        id: project_version
        uses: its404/get-flutter-version@v1.0.0
        
      - name: Download apks
        uses: actions/download-artifact@v4
        with:
          name: publish-artifacts
          path: build/app/outputs/flutter-apk

      - name: Download appbundle
        uses: actions/download-artifact@v4
        with:
          name: publish-artifacts
          path: build/app/outputs/bundle/prodRelease

      - name: Release Binary
        uses: ncipollo/release-action@v3
        with:
          artifacts: "build/app/outputs/bundle/release/*.aab, build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ steps.project_version.outputs.version_number }}+${{steps.project_version.outputs.build_number}}-${{github.run_number}}
          name: "Release ${{ steps.project_version.outputs.version_number }}+${{steps.project_version.outputs.build_number}}"
          generateReleaseNotes: true
